### ISSUE TITLE
Name of SDK

### ISSUE THREAD

**Issue by perrins** [ibm-bluemix-mobile-services/bms-clientsdk-swift-objectstore#1]
The SDK needs to run in both an Mobile Client and a Swift @IBM runtime as a server and continue to use the same pattern of API, the SDK should be intelligent enough to work through a proxy for more complicated use cases and the client SDK should understand UIImage and other iOS classes that would be used by a client developer

**Comment by AntonAleksandrov** [comment]
SDK supports iOS/OSX and Linux.
